# This playbook responsible to install all the necessary packages 
# and cloning the git repository of the Node Weight Tracker application

---
  - name: "Update all apt packages"
    apt: upgrade=dist force_apt_get=yes

  - name: "Install nodejs"
    apt:
      update_cache: yes
      name: nodejs
      state: present

  - name: "Update nodejs package"
    shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

  - name: "Clone git repository"
    git:
      repo: https://github.com/Gridin94/bootcamp-app
      dest: /home/azureuser/bootcamp-app/
      clone: yes
      update: yes
    register: git_finished

  - name: "Install NPM"
    shell: sudo npm install
    args:
      chdir: /home/azureuser/bootcamp-app/
    when: git_finished.changed
    register: npminstall_finished

  - name: "run NPM i"
    shell: sudo npm i
    args:
      chdir: /home/azureuser/bootcamp-app/
    when: npminstall_finished.changed
    register: npmi_finished

  - name: "Install PM2"
    npm:
      name: pm2
      global: yes
      state: present
    when: npmi_finished.changed